### ISSUE TITLE
Nadoknada

### ISSUE THREAD

**Issue by dsenta00** [petarculav/Strukture-Podataka#2]
Pozdrav Petre,

Dođi nadoknadit zadatak 11 u četvrtak.

S poštovanjem,
Duje

**Comment by petarculav** [comment]
Pozdrav profesore, 
Vježbu sam napisao ali nisam jos doradio te ju commitao.
Mogu li je ikako commitati veceras te izbjeci nadoknadu?
Lp, Petar Ćulav

**Comment by dsenta00** [comment]
Može, uradi tako.

S poštovanjem,
Duje
